export enum MessageType {

  SOCKET_STATUS = "SOCKET_STATUS",
  SAVE_USER_REQUEST = "SAVE_USER_REQUEST",

  MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST",
  MOVIE_LIST_RESPONSE = "MOVIE_LIST_RESPONSE",
  MOVIE_LIST_UPDATE = "MOVIE_LIST_UPDATE",

  MOVIE_ROOMS_REQUEST = "MOVIE_ROOMS_REQUEST",
  MOVIE_ROOMS_RESPONSE = "MOVIE_ROOMS_RESPONSE",
  MOVIE_ROOMS_UPDATE = "MOVIE_ROOMS_UPDATE",

  MOVIE_ROOM_REQUEST = "MOVIE_ROOM_REQUEST",
  MOVIE_ROOM_WITH_ID_REQUEST = "MOVIE_ROOM_WITH_ID_REQUEST",
  MOVIE_ROOM_RESPONSE = "MOVIE_ROOM_RESPONSE",
  MOVIE_ROOM_UPDATE = "MOVIE_ROOM_UPDATE",

  MOVIE_STREAM_REQUEST = "MOVIE_STREAM_REQUEST",
  MOVIE_STREAM_RESPONSE = "MOVIE_STREAM_RESPONSE",
  MOVIE_STREAM_UPDATE = "MOVIE_STREAM_UPDATE",

  MOVIE_CHAT_REQUEST = "MOVIE_CHAT_REQUEST",
  MOVIE_CHAT_RESPONSE = "MOVIE_CHAT_RESPONSE",
  MOVIE_CHAT_UPDATE = "MOVIE_CHAT_UPDATE",

  SEND_CHAT_MESSAGE_REQUEST = "SEND_CHAT_MESSAGE_REQUEST",
  CHAT_MESSAGES_REQUEST = "CHAT_MESSAGES_REQUEST",
  CHAT_MESSAGES_RESPONSE = "CHAT_MESSAGES_RESPONSE",
  CHAT_MESSAGE_UPDATE = "CHAT_MESSAGE_UPDATE",

  SEND_MOVIE_COMMENT_REQUEST = "SEND_MOVIE_COMMENT_REQUEST",
  MOVIE_COMMENTS_REQUEST = "MOVIE_COMMENTS_REQUEST",
  MOVIE_COMMENTS_RESPONSE = "MOVIE_COMMENTS_RESPONSE",
  MOVIE_COMMENT_UPDATE = "MOVIE_COMMENT_UPDATE",

  MOVIE_ROOM_PAUSE_REQUEST = "MOVIE_ROOM_PAUSE_REQUEST",
  MOVIE_ROOM_PAUSE_UPDATE = "MOVIE_ROOM_PAUSE_UPDATE",

  MOVIE_ROOM_PLAY_REQUEST = "MOVIE_ROOM_PLAY_REQUEST",
  MOVIE_ROOM_PLAY_UPDATE = "MOVIE_ROOM_PLAY_UPDATE",

  MOVIE_ROOM_SEEK_REQUEST = "MOVIE_ROOM_SEEK_REQUEST",
  MOVIE_ROOM_SEEK_UPDATE = "MOVIE_ROOM_SEEK_UPDATE",

  MOVIE_CLOSE_REQUEST = "MOVIE_CLOSE_REQUEST",
  MOVIE_CLOSE_RESPONSE = "MOVIE_CLOSE_RESPONSE",

  CONNECT_AUDIO_REQUEST = "CONNECT_AUDIO_REQUEST",
  DISCONNECT_AUDIO_REQUEST = "DISCONNECT_AUDIO_REQUEST",
  CONNECT_VIDEO_REQUEST = "CONNECT_VIDEO_REQUEST",
  DISCONNECT_VIDEO_REQUEST = "DISCONNECT_VIDEO_REQUEST",

  VIDEO_INFO_UPDATE = "VIDEO_INFO_UPDATE",

  SOCKET_EVENT_PEER_MESSAGE = "SOCKET_EVENT_PEER_MESSAGE",
  SOCKET_EVENT_PEER_CONNECTED = "SOCKET_EVENT_PEER_CONNECTED",
  SOCKET_EVENT_PEER_DISCONNECTED = "SOCKET_EVENT_PEER_DISCONNECTED",
  SOCKET_EVENT_CONNECT_TO_ROOM = "SOCKET_EVENT_CONNECT_TO_ROOM",

  // hmm............... idk if personal is needed or doable in the current implementation
  MOVIE_CLOSE_PERSONAL_REQUEST = "MOVIE_CLOSE_PERSONAL_REQUEST",
  MOVIE_CLOSE_PERSONAL_RESPONSE = "MOVIE_CLOSE_PERSONAL_RESPONSE"
}
